### ISSUE TITLE
webhook works but plugin exception is thrown (service.log)

### ISSUE THREAD

**Issue by jeeslo** [bageera/rundeck-team-webhook#1]
Hello all,

The webhook works and notifications are received to the team channel, however an ERROR gets logged in to /var/log/rundeck/service.log

`ERROR NotificationService: Error sending notification: Notification{eventTrigger='onsuccess', type='TeamkNotification', content='{"webhook_url":"https://outlook.office.com/webhook/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/IncomingWebhook/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"}'}: class com.bitplaces.rundeck.plugins.team.TeamNotificationPluginException: Unknown status returned from Microsoft Teams API: [1].
payload=%0A%0A%0A%7B%0A++%22text%22%3A+%22Execution+%23%5B77%5D%28https%3A%2F%2Frundekhost.local%3A8443%2Fproject%2FTesting%2Fexecution%2Ffollow%2F77%29+of+job+%5B0+-+Integration+%2F+test%5D%28https%3A%2F%2Frundekhost.local%3A8443%2Fproject%2FTesting%2Fjob%2Fshow%2F4a2d738e-60f3-49e4-bb44-ee15cf6f1b35%29%22%2C%0A++%22title%22%3A+%22Rundeck+Job+0+-+Integration+%2F+test%22%2C%0A++%22themeColor%22%3A+%22439e12%22%2C%0A++%22sections%22%3A+%5B%0A++%7B%0A++++++%22title%22%3A+%22Job+Details%22%2C%0A++++++%22facts%22%3A+%5B%0A++++++++%7B%0A++++++++++%22name%22%3A+%22Job+Name%22%2C%0A++++++++++%22value%22%3A+%220+-+Integration+%2F+test%22%0A++++++++%7D%2C%0A++++++++%7B%0A++++++++++%22name%22%3A+%22Job+Status%22%2C%0A++++++++++%22value%22%3A+%22succeeded%22%0A++++++++%7D%2C%0A++++++++%7B%0A++++++++++%22name%22%3A+%22Started+By%3A%22%2C%0A++++++++++%22value%22%3A+%22jescuder%22%0A++++++++%7D%0A++++++%5D%0A++++%7D%0A++%5D%2C%0A++%22potentialAction%22%3A+%5B%0A++++%7B%0A++++++%22%40context%22%3A+%22http%3A%2F%2Fschema.org%22%2C%0A++++++%22%40type%22%3A+%22ViewAction%22%2C%0A++++++%22name%22%3A+%22View+in+Rundeck%22%2C%0A++++++%22target%22%3A+%5B%22https%3A%2F%2Frundekhost.local%3A8443%2Fproject%2FTesting%2Fjob%2Fshow%2F4a2d738e-60f3-49e4-bb44-ee15cf6f1b35%22%5D%0A++++%7D%0A++%5D%0A%7D%0A
com.bitplaces.rundeck.plugins.team.TeamNotificationPluginException: Unknown status returned from Microsoft Teams API: [1].
payload=%0A%0A%0A%7B%0A++%22text%22%3A+%22Execution+%23%5B77%5D%28https%3A%2F%2Frundekhost.local%3A8443%2Fproject%2FTesting%2Fexecution%2Ffollow%2F77%29+of+job+%5B0+-+Integration+%2F+test%5D%28https%3A%2F%2Frundekhost.local%3A8443%2Fproject%2FTesting%2Fjob%2Fshow%2F4a2d738e-60f3-49e4-bb44-ee15cf6f1b35%29%22%2C%0A++%22title%22%3A+%22Rundeck+Job+0+-+Integration+%2F+test%22%2C%0A++%22themeColor%22%3A+%22439e12%22%2C%0A++%22sections%22%3A+%5B%0A++%7B%0A++++++%22title%22%3A+%22Job+Details%22%2C%0A++++++%22facts%22%3A+%5B%0A++++++++%7B%0A++++++++++%22name%22%3A+%22Job+Name%22%2C%0A++++++++++%22value%22%3A+%220+-+Integration+%2F+test%22%0A++++++++%7D%2C%0A++++++++%7B%0A++++++++++%22name%22%3A+%22Job+Status%22%2C%0A++++++++++%22value%22%3A+%22succeeded%22%0A++++++++%7D%2C%0A++++++++%7B%0A++++++++++%22name%22%3A+%22Started+By%3A%22%2C%0A++++++++++%22value%22%3A+%22user%22%0A++++++++%7D%0A++++++%5D%0A++++%7D%0A++%5D%2C%0A++%22potentialAction%22%3A+%5B%0A++++%7B%0A++++++%22%40context%22%3A+%22http%3A%2F%2Fschema.org%22%2C%0A++++++%22%40type%22%3A+%22ViewAction%22%2C%0A++++++%22name%22%3A+%22View+in+Rundeck%22%2C%0A++++++%22target%22%3A+%5B%22https%3A%2F%2Frundekhost.local%3A8443%2Fproject%2FTesting%2Fjob%2Fshow%2F4a2d738e-60f3-49e4-bb44-ee15cf6f1b35%22%5D%0A++++%7D%0A++%5D%0A%7D%0A
        at com.bitplaces.rundeck.plugins.team.TeamNotificationPlugin.postNotification(TeamNotificationPlugin.java:126)
        at rundeck.services.NotificationService.triggerPlugin(NotificationService.groovy:525)
        at rundeck.services.NotificationService$_triggerJobNotification_closure9.doCall(NotificationService.groovy:387)
        at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:175)
        at rundeck.services.NotificationService$_triggerJobNotification_closure5.doCall(NotificationService.groovy:117)
        at rundeck.services.NotificationService.triggerJobNotification(NotificationService.groovy:114)
        at rundeck.services.ExecutionService$_saveExecutionState_closure64.doCall(ExecutionService.groovy:2610)
        at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:2511)
        at rundeck.quartzjobs.ExecutionJob$_saveState_closure4.doCall(ExecutionJob.groovy:548)
        at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:487)
        at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:558)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:166)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:93)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:92)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
INFO  ExecutionService: updated scheduled Execution`

- Rundeck version: 2.10.6
- OS: CentOS 7
- Plugin version: 0.6

**Comment by jeeslo** [comment]
I tried after compiling it using rundeck-core: 2.10.6 (defined in build.gradle) but same result

**Comment by jeeslo** [comment]
PR raised: https://github.com/bageera/rundeck-team-webhook/pull/3
